

#ifndef __CUST_GPIO_BOOT_H__
#define __CUST_GPIO_BOOT_H__


//Configureation for Pin 0
#define GPIO0_MODE      GPIO_MODE_DEFAULT
#define GPIO0_DIR       GPIO_DIR_IN
#define GPIO0_PULLEN    GPIO_PULL_ENABLE
#define GPIO0_PULL      GPIO_PULL_DOWN
#define GPIO0_DATAOUT   GPIO_OUT_ZERO
#define GPIO0_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 1
#define GPIO1_MODE      GPIO_MODE_DEFAULT
#define GPIO1_DIR       GPIO_DIR_IN
#define GPIO1_PULLEN    GPIO_PULL_ENABLE
#define GPIO1_PULL      GPIO_PULL_DOWN
#define GPIO1_DATAOUT   GPIO_OUT_ZERO
#define GPIO1_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 2
#define GPIO2_MODE      GPIO_MODE_00
#define GPIO2_DIR       GPIO_DIR_OUT
#define GPIO2_PULLEN    GPIO_PULL_DISABLE
#define GPIO2_PULL      GPIO_PULL_DOWN
#define GPIO2_DATAOUT   GPIO_OUT_ZERO
#define GPIO2_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 3
#define GPIO3_MODE      GPIO_MODE_DEFAULT
#define GPIO3_DIR       GPIO_DIR_IN
#define GPIO3_PULLEN    GPIO_PULL_ENABLE
#define GPIO3_PULL      GPIO_PULL_DOWN
#define GPIO3_DATAOUT   GPIO_OUT_ZERO
#define GPIO3_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 4
#define GPIO4_MODE      GPIO_MODE_DEFAULT
#define GPIO4_DIR       GPIO_DIR_IN
#define GPIO4_PULLEN    GPIO_PULL_ENABLE
#define GPIO4_PULL      GPIO_PULL_DOWN
#define GPIO4_DATAOUT   GPIO_OUT_ZERO
#define GPIO4_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 5
#define GPIO5_MODE      GPIO_MODE_DEFAULT
#define GPIO5_DIR       GPIO_DIR_IN
#define GPIO5_PULLEN    GPIO_PULL_ENABLE
#define GPIO5_PULL      GPIO_PULL_DOWN
#define GPIO5_DATAOUT   GPIO_OUT_ZERO
#define GPIO5_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 6
#define GPIO6_MODE      GPIO_MODE_DEFAULT
#define GPIO6_DIR       GPIO_DIR_IN
#define GPIO6_PULLEN    GPIO_PULL_ENABLE
#define GPIO6_PULL      GPIO_PULL_DOWN
#define GPIO6_DATAOUT   GPIO_OUT_ZERO
#define GPIO6_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 7
#define GPIO7_MODE      GPIO_MODE_DEFAULT
#define GPIO7_DIR       GPIO_DIR_IN
#define GPIO7_PULLEN    GPIO_PULL_ENABLE
#define GPIO7_PULL      GPIO_PULL_DOWN
#define GPIO7_DATAOUT   GPIO_OUT_ZERO
#define GPIO7_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 8
#define GPIO8_MODE      GPIO_MODE_DEFAULT
#define GPIO8_DIR       GPIO_DIR_IN
#define GPIO8_PULLEN    GPIO_PULL_ENABLE
#define GPIO8_PULL      GPIO_PULL_DOWN
#define GPIO8_DATAOUT   GPIO_OUT_ZERO
#define GPIO8_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 9
#define GPIO9_MODE      GPIO_MODE_DEFAULT
#define GPIO9_DIR       GPIO_DIR_IN
#define GPIO9_PULLEN    GPIO_PULL_ENABLE
#define GPIO9_PULL      GPIO_PULL_DOWN
#define GPIO9_DATAOUT   GPIO_OUT_ZERO
#define GPIO9_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 10
#define GPIO10_MODE      GPIO_MODE_DEFAULT
#define GPIO10_DIR       GPIO_DIR_IN
#define GPIO10_PULLEN    GPIO_PULL_ENABLE
#define GPIO10_PULL      GPIO_PULL_DOWN
#define GPIO10_DATAOUT   GPIO_OUT_ZERO
#define GPIO10_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 11
#define GPIO11_MODE      GPIO_MODE_DEFAULT
#define GPIO11_DIR       GPIO_DIR_IN
#define GPIO11_PULLEN    GPIO_PULL_ENABLE
#define GPIO11_PULL      GPIO_PULL_DOWN
#define GPIO11_DATAOUT   GPIO_OUT_ZERO
#define GPIO11_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 12
#define GPIO12_MODE      GPIO_MODE_DEFAULT
#define GPIO12_DIR       GPIO_DIR_IN
#define GPIO12_PULLEN    GPIO_PULL_ENABLE
#define GPIO12_PULL      GPIO_PULL_DOWN
#define GPIO12_DATAOUT   GPIO_OUT_ZERO
#define GPIO12_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 13
#define GPIO13_MODE      GPIO_MODE_DEFAULT
#define GPIO13_DIR       GPIO_DIR_IN
#define GPIO13_PULLEN    GPIO_PULL_ENABLE
#define GPIO13_PULL      GPIO_PULL_DOWN
#define GPIO13_DATAOUT   GPIO_OUT_ZERO
#define GPIO13_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 14
#define GPIO14_MODE      GPIO_MODE_DEFAULT
#define GPIO14_DIR       GPIO_DIR_IN
#define GPIO14_PULLEN    GPIO_PULL_ENABLE
#define GPIO14_PULL      GPIO_PULL_DOWN
#define GPIO14_DATAOUT   GPIO_OUT_ZERO
#define GPIO14_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 15
#define GPIO15_MODE      GPIO_MODE_DEFAULT
#define GPIO15_DIR       GPIO_DIR_IN
#define GPIO15_PULLEN    GPIO_PULL_ENABLE
#define GPIO15_PULL      GPIO_PULL_DOWN
#define GPIO15_DATAOUT   GPIO_OUT_ZERO
#define GPIO15_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 16
#define GPIO16_MODE      GPIO_MODE_DEFAULT
#define GPIO16_DIR       GPIO_DIR_IN
#define GPIO16_PULLEN    GPIO_PULL_ENABLE
#define GPIO16_PULL      GPIO_PULL_DOWN
#define GPIO16_DATAOUT   GPIO_OUT_ZERO
#define GPIO16_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 17
#define GPIO17_MODE      GPIO_MODE_01
#define GPIO17_DIR       GPIO_DIR_IN
#define GPIO17_PULLEN    GPIO_PULL_ENABLE
#define GPIO17_PULL      GPIO_PULL_DOWN
#define GPIO17_DATAOUT   GPIO_OUT_ZERO
#define GPIO17_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 18
#define GPIO18_MODE      GPIO_MODE_01
#define GPIO18_DIR       GPIO_DIR_IN
#define GPIO18_PULLEN    GPIO_PULL_ENABLE
#define GPIO18_PULL      GPIO_PULL_DOWN
#define GPIO18_DATAOUT   GPIO_OUT_ZERO
#define GPIO18_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 19
#define GPIO19_MODE      GPIO_MODE_DEFAULT
#define GPIO19_DIR       GPIO_DIR_IN
#define GPIO19_PULLEN    GPIO_PULL_ENABLE
#define GPIO19_PULL      GPIO_PULL_DOWN
#define GPIO19_DATAOUT   GPIO_OUT_ZERO
#define GPIO19_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 20
#define GPIO20_MODE      GPIO_MODE_DEFAULT
#define GPIO20_DIR       GPIO_DIR_IN
#define GPIO20_PULLEN    GPIO_PULL_ENABLE
#define GPIO20_PULL      GPIO_PULL_DOWN
#define GPIO20_DATAOUT   GPIO_OUT_ZERO
#define GPIO20_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 21
#define GPIO21_MODE      GPIO_MODE_01
#define GPIO21_DIR       GPIO_DIR_IN
#define GPIO21_PULLEN    GPIO_PULL_ENABLE
#define GPIO21_PULL      GPIO_PULL_DOWN
#define GPIO21_DATAOUT   GPIO_OUT_ZERO
#define GPIO21_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 22
#define GPIO22_MODE      GPIO_MODE_01
#define GPIO22_DIR       GPIO_DIR_IN
#define GPIO22_PULLEN    GPIO_PULL_ENABLE
#define GPIO22_PULL      GPIO_PULL_UP
#define GPIO22_DATAOUT   GPIO_OUT_ZERO
#define GPIO22_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 23
#define GPIO23_MODE      GPIO_MODE_01
#define GPIO23_DIR       GPIO_DIR_IN
#define GPIO23_PULLEN    GPIO_PULL_DISABLE
#define GPIO23_PULL      GPIO_PULL_DOWN
#define GPIO23_DATAOUT   GPIO_OUT_ZERO
#define GPIO23_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 24
#define GPIO24_MODE      GPIO_MODE_DEFAULT
#define GPIO24_DIR       GPIO_DIR_IN
#define GPIO24_PULLEN    GPIO_PULL_ENABLE
#define GPIO24_PULL      GPIO_PULL_DOWN
#define GPIO24_DATAOUT   GPIO_OUT_ZERO
#define GPIO24_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 25
#define GPIO25_MODE      GPIO_MODE_DEFAULT
#define GPIO25_DIR       GPIO_DIR_IN
#define GPIO25_PULLEN    GPIO_PULL_ENABLE
#define GPIO25_PULL      GPIO_PULL_DOWN
#define GPIO25_DATAOUT   GPIO_OUT_ZERO
#define GPIO25_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 26
#define GPIO26_MODE      GPIO_MODE_DEFAULT
#define GPIO26_DIR       GPIO_DIR_IN
#define GPIO26_PULLEN    GPIO_PULL_ENABLE
#define GPIO26_PULL      GPIO_PULL_DOWN
#define GPIO26_DATAOUT   GPIO_OUT_ZERO
#define GPIO26_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 27
#define GPIO27_MODE      GPIO_MODE_DEFAULT
#define GPIO27_DIR       GPIO_DIR_IN
#define GPIO27_PULLEN    GPIO_PULL_ENABLE
#define GPIO27_PULL      GPIO_PULL_DOWN
#define GPIO27_DATAOUT   GPIO_OUT_ZERO
#define GPIO27_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 28
#define GPIO28_MODE      GPIO_MODE_01
#define GPIO28_DIR       GPIO_DIR_IN
#define GPIO28_PULLEN    GPIO_PULL_ENABLE
#define GPIO28_PULL      GPIO_PULL_UP
#define GPIO28_DATAOUT   GPIO_OUT_ZERO
#define GPIO28_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 29
#define GPIO29_MODE      GPIO_MODE_DEFAULT
#define GPIO29_DIR       GPIO_DIR_IN
#define GPIO29_PULLEN    GPIO_PULL_ENABLE
#define GPIO29_PULL      GPIO_PULL_DOWN
#define GPIO29_DATAOUT   GPIO_OUT_ZERO
#define GPIO29_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 30
#define GPIO30_MODE      GPIO_MODE_DEFAULT
#define GPIO30_DIR       GPIO_DIR_IN
#define GPIO30_PULLEN    GPIO_PULL_ENABLE
#define GPIO30_PULL      GPIO_PULL_DOWN
#define GPIO30_DATAOUT   GPIO_OUT_ZERO
#define GPIO30_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 31
#define GPIO31_MODE      GPIO_MODE_DEFAULT
#define GPIO31_DIR       GPIO_DIR_IN
#define GPIO31_PULLEN    GPIO_PULL_ENABLE
#define GPIO31_PULL      GPIO_PULL_DOWN
#define GPIO31_DATAOUT   GPIO_OUT_ZERO
#define GPIO31_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 32
#define GPIO32_MODE      GPIO_MODE_DEFAULT
#define GPIO32_DIR       GPIO_DIR_IN
#define GPIO32_PULLEN    GPIO_PULL_ENABLE
#define GPIO32_PULL      GPIO_PULL_DOWN
#define GPIO32_DATAOUT   GPIO_OUT_ZERO
#define GPIO32_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 33
#define GPIO33_MODE      GPIO_MODE_DEFAULT
#define GPIO33_DIR       GPIO_DIR_IN
#define GPIO33_PULLEN    GPIO_PULL_ENABLE
#define GPIO33_PULL      GPIO_PULL_DOWN
#define GPIO33_DATAOUT   GPIO_OUT_ZERO
#define GPIO33_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 34
#define GPIO34_MODE      GPIO_MODE_01
#define GPIO34_DIR       GPIO_DIR_IN
#define GPIO34_PULLEN    GPIO_PULL_ENABLE
#define GPIO34_PULL      GPIO_PULL_DOWN
#define GPIO34_DATAOUT   GPIO_OUT_ZERO
#define GPIO34_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 35
#define GPIO35_MODE      GPIO_MODE_01
#define GPIO35_DIR       GPIO_DIR_IN
#define GPIO35_PULLEN    GPIO_PULL_ENABLE
#define GPIO35_PULL      GPIO_PULL_DOWN
#define GPIO35_DATAOUT   GPIO_OUT_ZERO
#define GPIO35_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 36
#define GPIO36_MODE      GPIO_MODE_DEFAULT
#define GPIO36_DIR       GPIO_DIR_IN
#define GPIO36_PULLEN    GPIO_PULL_ENABLE
#define GPIO36_PULL      GPIO_PULL_DOWN
#define GPIO36_DATAOUT   GPIO_OUT_ZERO
#define GPIO36_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 37
#define GPIO37_MODE      GPIO_MODE_DEFAULT
#define GPIO37_DIR       GPIO_DIR_IN
#define GPIO37_PULLEN    GPIO_PULL_ENABLE
#define GPIO37_PULL      GPIO_PULL_DOWN
#define GPIO37_DATAOUT   GPIO_OUT_ZERO
#define GPIO37_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 38
#define GPIO38_MODE      GPIO_MODE_DEFAULT
#define GPIO38_DIR       GPIO_DIR_IN
#define GPIO38_PULLEN    GPIO_PULL_ENABLE
#define GPIO38_PULL      GPIO_PULL_DOWN
#define GPIO38_DATAOUT   GPIO_OUT_ZERO
#define GPIO38_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 39
#define GPIO39_MODE      GPIO_MODE_DEFAULT
#define GPIO39_DIR       GPIO_DIR_IN
#define GPIO39_PULLEN    GPIO_PULL_ENABLE
#define GPIO39_PULL      GPIO_PULL_DOWN
#define GPIO39_DATAOUT   GPIO_OUT_ZERO
#define GPIO39_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 40
#define GPIO40_MODE      GPIO_MODE_DEFAULT
#define GPIO40_DIR       GPIO_DIR_IN
#define GPIO40_PULLEN    GPIO_PULL_ENABLE
#define GPIO40_PULL      GPIO_PULL_DOWN
#define GPIO40_DATAOUT   GPIO_OUT_ZERO
#define GPIO40_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 41
#define GPIO41_MODE      GPIO_MODE_DEFAULT
#define GPIO41_DIR       GPIO_DIR_IN
#define GPIO41_PULLEN    GPIO_PULL_ENABLE
#define GPIO41_PULL      GPIO_PULL_DOWN
#define GPIO41_DATAOUT   GPIO_OUT_ZERO
#define GPIO41_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 42
#define GPIO42_MODE      GPIO_MODE_DEFAULT
#define GPIO42_DIR       GPIO_DIR_IN
#define GPIO42_PULLEN    GPIO_PULL_ENABLE
#define GPIO42_PULL      GPIO_PULL_DOWN
#define GPIO42_DATAOUT   GPIO_OUT_ZERO
#define GPIO42_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 43
#define GPIO43_MODE      GPIO_MODE_DEFAULT
#define GPIO43_DIR       GPIO_DIR_IN
#define GPIO43_PULLEN    GPIO_PULL_ENABLE
#define GPIO43_PULL      GPIO_PULL_DOWN
#define GPIO43_DATAOUT   GPIO_OUT_ZERO
#define GPIO43_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 44
#define GPIO44_MODE      GPIO_MODE_DEFAULT
#define GPIO44_DIR       GPIO_DIR_IN
#define GPIO44_PULLEN    GPIO_PULL_ENABLE
#define GPIO44_PULL      GPIO_PULL_DOWN
#define GPIO44_DATAOUT   GPIO_OUT_ZERO
#define GPIO44_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 45
#define GPIO45_MODE      GPIO_MODE_DEFAULT
#define GPIO45_DIR       GPIO_DIR_IN
#define GPIO45_PULLEN    GPIO_PULL_ENABLE
#define GPIO45_PULL      GPIO_PULL_DOWN
#define GPIO45_DATAOUT   GPIO_OUT_ZERO
#define GPIO45_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 46
#define GPIO46_MODE      GPIO_MODE_DEFAULT
#define GPIO46_DIR       GPIO_DIR_IN
#define GPIO46_PULLEN    GPIO_PULL_ENABLE
#define GPIO46_PULL      GPIO_PULL_DOWN
#define GPIO46_DATAOUT   GPIO_OUT_ZERO
#define GPIO46_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 47
#define GPIO47_MODE      GPIO_MODE_DEFAULT
#define GPIO47_DIR       GPIO_DIR_IN
#define GPIO47_PULLEN    GPIO_PULL_ENABLE
#define GPIO47_PULL      GPIO_PULL_DOWN
#define GPIO47_DATAOUT   GPIO_OUT_ZERO
#define GPIO47_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 48
#define GPIO48_MODE      GPIO_MODE_DEFAULT
#define GPIO48_DIR       GPIO_DIR_IN
#define GPIO48_PULLEN    GPIO_PULL_ENABLE
#define GPIO48_PULL      GPIO_PULL_DOWN
#define GPIO48_DATAOUT   GPIO_OUT_ZERO
#define GPIO48_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 49
#define GPIO49_MODE      GPIO_MODE_DEFAULT
#define GPIO49_DIR       GPIO_DIR_IN
#define GPIO49_PULLEN    GPIO_PULL_ENABLE
#define GPIO49_PULL      GPIO_PULL_DOWN
#define GPIO49_DATAOUT   GPIO_OUT_ZERO
#define GPIO49_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 50
#define GPIO50_MODE      GPIO_MODE_DEFAULT
#define GPIO50_DIR       GPIO_DIR_IN
#define GPIO50_PULLEN    GPIO_PULL_ENABLE
#define GPIO50_PULL      GPIO_PULL_DOWN
#define GPIO50_DATAOUT   GPIO_OUT_ZERO
#define GPIO50_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 51
#define GPIO51_MODE      GPIO_MODE_DEFAULT
#define GPIO51_DIR       GPIO_DIR_IN
#define GPIO51_PULLEN    GPIO_PULL_ENABLE
#define GPIO51_PULL      GPIO_PULL_DOWN
#define GPIO51_DATAOUT   GPIO_OUT_ZERO
#define GPIO51_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 52
#define GPIO52_MODE      GPIO_MODE_DEFAULT
#define GPIO52_DIR       GPIO_DIR_IN
#define GPIO52_PULLEN    GPIO_PULL_ENABLE
#define GPIO52_PULL      GPIO_PULL_DOWN
#define GPIO52_DATAOUT   GPIO_OUT_ZERO
#define GPIO52_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 53
#define GPIO53_MODE      GPIO_MODE_DEFAULT
#define GPIO53_DIR       GPIO_DIR_IN
#define GPIO53_PULLEN    GPIO_PULL_ENABLE
#define GPIO53_PULL      GPIO_PULL_DOWN
#define GPIO53_DATAOUT   GPIO_OUT_ZERO
#define GPIO53_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 54
#define GPIO54_MODE      GPIO_MODE_02
#define GPIO54_DIR       GPIO_DIR_IN
#define GPIO54_PULLEN    GPIO_PULL_ENABLE
#define GPIO54_PULL      GPIO_PULL_UP
#define GPIO54_DATAOUT   GPIO_OUT_ZERO
#define GPIO54_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 55
#define GPIO55_MODE      GPIO_MODE_03
#define GPIO55_DIR       GPIO_DIR_IN
#define GPIO55_PULLEN    GPIO_PULL_ENABLE
#define GPIO55_PULL      GPIO_PULL_UP
#define GPIO55_DATAOUT   GPIO_OUT_ZERO
#define GPIO55_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 56
#define GPIO56_MODE      GPIO_MODE_DEFAULT
#define GPIO56_DIR       GPIO_DIR_IN
#define GPIO56_PULLEN    GPIO_PULL_ENABLE
#define GPIO56_PULL      GPIO_PULL_DOWN
#define GPIO56_DATAOUT   GPIO_OUT_ZERO
#define GPIO56_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 57
#define GPIO57_MODE      GPIO_MODE_02
#define GPIO57_DIR       GPIO_DIR_IN
#define GPIO57_PULLEN    GPIO_PULL_ENABLE
#define GPIO57_PULL      GPIO_PULL_DOWN
#define GPIO57_DATAOUT   GPIO_OUT_ZERO
#define GPIO57_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 58
#define GPIO58_MODE      GPIO_MODE_DEFAULT
#define GPIO58_DIR       GPIO_DIR_IN
#define GPIO58_PULLEN    GPIO_PULL_ENABLE
#define GPIO58_PULL      GPIO_PULL_UP
#define GPIO58_DATAOUT   GPIO_OUT_ZERO
#define GPIO58_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 59
#define GPIO59_MODE      GPIO_MODE_01
#define GPIO59_DIR       GPIO_DIR_IN
#define GPIO59_PULLEN    GPIO_PULL_ENABLE
#define GPIO59_PULL      GPIO_PULL_UP
#define GPIO59_DATAOUT   GPIO_OUT_ZERO
#define GPIO59_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 60
#define GPIO60_MODE      GPIO_MODE_01
#define GPIO60_DIR       GPIO_DIR_IN
#define GPIO60_PULLEN    GPIO_PULL_ENABLE
#define GPIO60_PULL      GPIO_PULL_UP
#define GPIO60_DATAOUT   GPIO_OUT_ZERO
#define GPIO60_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 61
#define GPIO61_MODE      GPIO_MODE_01
#define GPIO61_DIR       GPIO_DIR_IN
#define GPIO61_PULLEN    GPIO_PULL_ENABLE
#define GPIO61_PULL      GPIO_PULL_UP
#define GPIO61_DATAOUT   GPIO_OUT_ZERO
#define GPIO61_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 62
#define GPIO62_MODE      GPIO_MODE_01
#define GPIO62_DIR       GPIO_DIR_IN
#define GPIO62_PULLEN    GPIO_PULL_ENABLE
#define GPIO62_PULL      GPIO_PULL_UP
#define GPIO62_DATAOUT   GPIO_OUT_ZERO
#define GPIO62_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 63
#define GPIO63_MODE      GPIO_MODE_01
#define GPIO63_DIR       GPIO_DIR_IN
#define GPIO63_PULLEN    GPIO_PULL_ENABLE
#define GPIO63_PULL      GPIO_PULL_UP
#define GPIO63_DATAOUT   GPIO_OUT_ZERO
#define GPIO63_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 64
#define GPIO64_MODE      GPIO_MODE_01
#define GPIO64_DIR       GPIO_DIR_IN
#define GPIO64_PULLEN    GPIO_PULL_ENABLE
#define GPIO64_PULL      GPIO_PULL_UP
#define GPIO64_DATAOUT   GPIO_OUT_ZERO
#define GPIO64_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 65
#define GPIO65_MODE      GPIO_MODE_01
#define GPIO65_DIR       GPIO_DIR_IN
#define GPIO65_PULLEN    GPIO_PULL_ENABLE
#define GPIO65_PULL      GPIO_PULL_DOWN
#define GPIO65_DATAOUT   GPIO_OUT_ZERO
#define GPIO65_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 66
#define GPIO66_MODE      GPIO_MODE_01
#define GPIO66_DIR       GPIO_DIR_IN
#define GPIO66_PULLEN    GPIO_PULL_ENABLE
#define GPIO66_PULL      GPIO_PULL_UP
#define GPIO66_DATAOUT   GPIO_OUT_ZERO
#define GPIO66_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 67
#define GPIO67_MODE      GPIO_MODE_01
#define GPIO67_DIR       GPIO_DIR_IN
#define GPIO67_PULLEN    GPIO_PULL_ENABLE
#define GPIO67_PULL      GPIO_PULL_UP
#define GPIO67_DATAOUT   GPIO_OUT_ZERO
#define GPIO67_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 68
#define GPIO68_MODE      GPIO_MODE_01
#define GPIO68_DIR       GPIO_DIR_IN
#define GPIO68_PULLEN    GPIO_PULL_ENABLE
#define GPIO68_PULL      GPIO_PULL_UP
#define GPIO68_DATAOUT   GPIO_OUT_ZERO
#define GPIO68_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 69
#define GPIO69_MODE      GPIO_MODE_01
#define GPIO69_DIR       GPIO_DIR_IN
#define GPIO69_PULLEN    GPIO_PULL_ENABLE
#define GPIO69_PULL      GPIO_PULL_UP
#define GPIO69_DATAOUT   GPIO_OUT_ZERO
#define GPIO69_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 70
#define GPIO70_MODE      GPIO_MODE_01
#define GPIO70_DIR       GPIO_DIR_IN
#define GPIO70_PULLEN    GPIO_PULL_ENABLE
#define GPIO70_PULL      GPIO_PULL_UP
#define GPIO70_DATAOUT   GPIO_OUT_ZERO
#define GPIO70_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 71
#define GPIO71_MODE      GPIO_MODE_01
#define GPIO71_DIR       GPIO_DIR_IN
#define GPIO71_PULLEN    GPIO_PULL_ENABLE
#define GPIO71_PULL      GPIO_PULL_UP
#define GPIO71_DATAOUT   GPIO_OUT_ZERO
#define GPIO71_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 72
#define GPIO72_MODE      GPIO_MODE_01
#define GPIO72_DIR       GPIO_DIR_IN
#define GPIO72_PULLEN    GPIO_PULL_ENABLE
#define GPIO72_PULL      GPIO_PULL_UP
#define GPIO72_DATAOUT   GPIO_OUT_ZERO
#define GPIO72_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 73
#define GPIO73_MODE      GPIO_MODE_01
#define GPIO73_DIR       GPIO_DIR_IN
#define GPIO73_PULLEN    GPIO_PULL_DISABLE
#define GPIO73_PULL      GPIO_PULL_DOWN
#define GPIO73_DATAOUT   GPIO_OUT_ZERO
#define GPIO73_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 74
#define GPIO74_MODE      GPIO_MODE_01
#define GPIO74_DIR       GPIO_DIR_IN
#define GPIO74_PULLEN    GPIO_PULL_DISABLE
#define GPIO74_PULL      GPIO_PULL_DOWN
#define GPIO74_DATAOUT   GPIO_OUT_ZERO
#define GPIO74_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 75
#define GPIO75_MODE      GPIO_MODE_01
#define GPIO75_DIR       GPIO_DIR_IN
#define GPIO75_PULLEN    GPIO_PULL_ENABLE
#define GPIO75_PULL      GPIO_PULL_DOWN
#define GPIO75_DATAOUT   GPIO_OUT_ZERO
#define GPIO75_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 76
#define GPIO76_MODE      GPIO_MODE_01
#define GPIO76_DIR       GPIO_DIR_IN
#define GPIO76_PULLEN    GPIO_PULL_ENABLE
#define GPIO76_PULL      GPIO_PULL_DOWN
#define GPIO76_DATAOUT   GPIO_OUT_ZERO
#define GPIO76_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 77
#define GPIO77_MODE      GPIO_MODE_01
#define GPIO77_DIR       GPIO_DIR_IN
#define GPIO77_PULLEN    GPIO_PULL_ENABLE
#define GPIO77_PULL      GPIO_PULL_DOWN
#define GPIO77_DATAOUT   GPIO_OUT_ZERO
#define GPIO77_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 78
#define GPIO78_MODE      GPIO_MODE_DEFAULT
#define GPIO78_DIR       GPIO_DIR_IN
#define GPIO78_PULLEN    GPIO_PULL_ENABLE
#define GPIO78_PULL      GPIO_PULL_DOWN
#define GPIO78_DATAOUT   GPIO_OUT_ZERO
#define GPIO78_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 79
#define GPIO79_MODE      GPIO_MODE_01
#define GPIO79_DIR       GPIO_DIR_IN
#define GPIO79_PULLEN    GPIO_PULL_ENABLE
#define GPIO79_PULL      GPIO_PULL_DOWN
#define GPIO79_DATAOUT   GPIO_OUT_ZERO
#define GPIO79_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 80
#define GPIO80_MODE      GPIO_MODE_DEFAULT
#define GPIO80_DIR       GPIO_DIR_IN
#define GPIO80_PULLEN    GPIO_PULL_ENABLE
#define GPIO80_PULL      GPIO_PULL_DOWN
#define GPIO80_DATAOUT   GPIO_OUT_ZERO
#define GPIO80_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 81
#define GPIO81_MODE      GPIO_MODE_DEFAULT
#define GPIO81_DIR       GPIO_DIR_IN
#define GPIO81_PULLEN    GPIO_PULL_ENABLE
#define GPIO81_PULL      GPIO_PULL_DOWN
#define GPIO81_DATAOUT   GPIO_OUT_ZERO
#define GPIO81_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 82
#define GPIO82_MODE      GPIO_MODE_DEFAULT
#define GPIO82_DIR       GPIO_DIR_IN
#define GPIO82_PULLEN    GPIO_PULL_ENABLE
#define GPIO82_PULL      GPIO_PULL_DOWN
#define GPIO82_DATAOUT   GPIO_OUT_ZERO
#define GPIO82_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 83
#define GPIO83_MODE      GPIO_MODE_DEFAULT
#define GPIO83_DIR       GPIO_DIR_IN
#define GPIO83_PULLEN    GPIO_PULL_ENABLE
#define GPIO83_PULL      GPIO_PULL_DOWN
#define GPIO83_DATAOUT   GPIO_OUT_ZERO
#define GPIO83_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 84
#define GPIO84_MODE      GPIO_MODE_DEFAULT
#define GPIO84_DIR       GPIO_DIR_IN
#define GPIO84_PULLEN    GPIO_PULL_ENABLE
#define GPIO84_PULL      GPIO_PULL_DOWN
#define GPIO84_DATAOUT   GPIO_OUT_ZERO
#define GPIO84_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 85
#define GPIO85_MODE      GPIO_MODE_DEFAULT
#define GPIO85_DIR       GPIO_DIR_IN
#define GPIO85_PULLEN    GPIO_PULL_ENABLE
#define GPIO85_PULL      GPIO_PULL_DOWN
#define GPIO85_DATAOUT   GPIO_OUT_ZERO
#define GPIO85_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 86
#define GPIO86_MODE      GPIO_MODE_DEFAULT
#define GPIO86_DIR       GPIO_DIR_IN
#define GPIO86_PULLEN    GPIO_PULL_ENABLE
#define GPIO86_PULL      GPIO_PULL_DOWN
#define GPIO86_DATAOUT   GPIO_OUT_ZERO
#define GPIO86_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 87
#define GPIO87_MODE      GPIO_MODE_01
#define GPIO87_DIR       GPIO_DIR_IN
#define GPIO87_PULLEN    GPIO_PULL_ENABLE
#define GPIO87_PULL      GPIO_PULL_UP
#define GPIO87_DATAOUT   GPIO_OUT_ZERO
#define GPIO87_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 88
#define GPIO88_MODE      GPIO_MODE_01
#define GPIO88_DIR       GPIO_DIR_IN
#define GPIO88_PULLEN    GPIO_PULL_ENABLE
#define GPIO88_PULL      GPIO_PULL_UP
#define GPIO88_DATAOUT   GPIO_OUT_ZERO
#define GPIO88_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 89
#define GPIO89_MODE      GPIO_MODE_01
#define GPIO89_DIR       GPIO_DIR_IN
#define GPIO89_PULLEN    GPIO_PULL_ENABLE
#define GPIO89_PULL      GPIO_PULL_UP
#define GPIO89_DATAOUT   GPIO_OUT_ZERO
#define GPIO89_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 90
#define GPIO90_MODE      GPIO_MODE_01
#define GPIO90_DIR       GPIO_DIR_IN
#define GPIO90_PULLEN    GPIO_PULL_ENABLE
#define GPIO90_PULL      GPIO_PULL_UP
#define GPIO90_DATAOUT   GPIO_OUT_ZERO
#define GPIO90_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 91
#define GPIO91_MODE      GPIO_MODE_01
#define GPIO91_DIR       GPIO_DIR_IN
#define GPIO91_PULLEN    GPIO_PULL_ENABLE
#define GPIO91_PULL      GPIO_PULL_UP
#define GPIO91_DATAOUT   GPIO_OUT_ZERO
#define GPIO91_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 92
#define GPIO92_MODE      GPIO_MODE_DEFAULT
#define GPIO92_DIR       GPIO_DIR_IN
#define GPIO92_PULLEN    GPIO_PULL_ENABLE
#define GPIO92_PULL      GPIO_PULL_DOWN
#define GPIO92_DATAOUT   GPIO_OUT_ZERO
#define GPIO92_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 93
#define GPIO93_MODE      GPIO_MODE_DEFAULT
#define GPIO93_DIR       GPIO_DIR_IN
#define GPIO93_PULLEN    GPIO_PULL_ENABLE
#define GPIO93_PULL      GPIO_PULL_DOWN
#define GPIO93_DATAOUT   GPIO_OUT_ZERO
#define GPIO93_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 94
#define GPIO94_MODE      GPIO_MODE_DEFAULT
#define GPIO94_DIR       GPIO_DIR_IN
#define GPIO94_PULLEN    GPIO_PULL_ENABLE
#define GPIO94_PULL      GPIO_PULL_DOWN
#define GPIO94_DATAOUT   GPIO_OUT_ZERO
#define GPIO94_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 95
#define GPIO95_MODE      GPIO_MODE_DEFAULT
#define GPIO95_DIR       GPIO_DIR_IN
#define GPIO95_PULLEN    GPIO_PULL_ENABLE
#define GPIO95_PULL      GPIO_PULL_DOWN
#define GPIO95_DATAOUT   GPIO_OUT_ZERO
#define GPIO95_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 96
#define GPIO96_MODE      GPIO_MODE_DEFAULT
#define GPIO96_DIR       GPIO_DIR_IN
#define GPIO96_PULLEN    GPIO_PULL_ENABLE
#define GPIO96_PULL      GPIO_PULL_DOWN
#define GPIO96_DATAOUT   GPIO_OUT_ZERO
#define GPIO96_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 97
#define GPIO97_MODE      GPIO_MODE_DEFAULT
#define GPIO97_DIR       GPIO_DIR_IN
#define GPIO97_PULLEN    GPIO_PULL_ENABLE
#define GPIO97_PULL      GPIO_PULL_DOWN
#define GPIO97_DATAOUT   GPIO_OUT_ZERO
#define GPIO97_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 98
#define GPIO98_MODE      GPIO_MODE_DEFAULT
#define GPIO98_DIR       GPIO_DIR_IN
#define GPIO98_PULLEN    GPIO_PULL_ENABLE
#define GPIO98_PULL      GPIO_PULL_DOWN
#define GPIO98_DATAOUT   GPIO_OUT_ZERO
#define GPIO98_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 99
#define GPIO99_MODE      GPIO_MODE_DEFAULT
#define GPIO99_DIR       GPIO_DIR_IN
#define GPIO99_PULLEN    GPIO_PULL_ENABLE
#define GPIO99_PULL      GPIO_PULL_DOWN
#define GPIO99_DATAOUT   GPIO_OUT_ZERO
#define GPIO99_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 100
#define GPIO100_MODE      GPIO_MODE_DEFAULT
#define GPIO100_DIR       GPIO_DIR_IN
#define GPIO100_PULLEN    GPIO_PULL_ENABLE
#define GPIO100_PULL      GPIO_PULL_DOWN
#define GPIO100_DATAOUT   GPIO_OUT_ZERO
#define GPIO100_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 101
#define GPIO101_MODE      GPIO_MODE_DEFAULT
#define GPIO101_DIR       GPIO_DIR_IN
#define GPIO101_PULLEN    GPIO_PULL_ENABLE
#define GPIO101_PULL      GPIO_PULL_DOWN
#define GPIO101_DATAOUT   GPIO_OUT_ZERO
#define GPIO101_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 102
#define GPIO102_MODE      GPIO_MODE_DEFAULT
#define GPIO102_DIR       GPIO_DIR_IN
#define GPIO102_PULLEN    GPIO_PULL_ENABLE
#define GPIO102_PULL      GPIO_PULL_DOWN
#define GPIO102_DATAOUT   GPIO_OUT_ZERO
#define GPIO102_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 103
#define GPIO103_MODE      GPIO_MODE_DEFAULT
#define GPIO103_DIR       GPIO_DIR_IN
#define GPIO103_PULLEN    GPIO_PULL_ENABLE
#define GPIO103_PULL      GPIO_PULL_DOWN
#define GPIO103_DATAOUT   GPIO_OUT_ZERO
#define GPIO103_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 104
#define GPIO104_MODE      GPIO_MODE_DEFAULT
#define GPIO104_DIR       GPIO_DIR_IN
#define GPIO104_PULLEN    GPIO_PULL_ENABLE
#define GPIO104_PULL      GPIO_PULL_DOWN
#define GPIO104_DATAOUT   GPIO_OUT_ZERO
#define GPIO104_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 105
#define GPIO105_MODE      GPIO_MODE_DEFAULT
#define GPIO105_DIR       GPIO_DIR_IN
#define GPIO105_PULLEN    GPIO_PULL_ENABLE
#define GPIO105_PULL      GPIO_PULL_DOWN
#define GPIO105_DATAOUT   GPIO_OUT_ZERO
#define GPIO105_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 106
#define GPIO106_MODE      GPIO_MODE_DEFAULT
#define GPIO106_DIR       GPIO_DIR_IN
#define GPIO106_PULLEN    GPIO_PULL_ENABLE
#define GPIO106_PULL      GPIO_PULL_DOWN
#define GPIO106_DATAOUT   GPIO_OUT_ZERO
#define GPIO106_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 107
#define GPIO107_MODE      GPIO_MODE_DEFAULT
#define GPIO107_DIR       GPIO_DIR_IN
#define GPIO107_PULLEN    GPIO_PULL_ENABLE
#define GPIO107_PULL      GPIO_PULL_DOWN
#define GPIO107_DATAOUT   GPIO_OUT_ZERO
#define GPIO107_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 108
#define GPIO108_MODE      GPIO_MODE_DEFAULT
#define GPIO108_DIR       GPIO_DIR_IN
#define GPIO108_PULLEN    GPIO_PULL_ENABLE
#define GPIO108_PULL      GPIO_PULL_DOWN
#define GPIO108_DATAOUT   GPIO_OUT_ZERO
#define GPIO108_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 109
#define GPIO109_MODE      GPIO_MODE_DEFAULT
#define GPIO109_DIR       GPIO_DIR_IN
#define GPIO109_PULLEN    GPIO_PULL_ENABLE
#define GPIO109_PULL      GPIO_PULL_DOWN
#define GPIO109_DATAOUT   GPIO_OUT_ZERO
#define GPIO109_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 110
#define GPIO110_MODE      GPIO_MODE_01
#define GPIO110_DIR       GPIO_DIR_IN
#define GPIO110_PULLEN    GPIO_PULL_DISABLE
#define GPIO110_PULL      GPIO_PULL_DOWN
#define GPIO110_DATAOUT   GPIO_OUT_ZERO
#define GPIO110_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 111
#define GPIO111_MODE      GPIO_MODE_01
#define GPIO111_DIR       GPIO_DIR_IN
#define GPIO111_PULLEN    GPIO_PULL_DISABLE
#define GPIO111_PULL      GPIO_PULL_DOWN
#define GPIO111_DATAOUT   GPIO_OUT_ZERO
#define GPIO111_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 112
#define GPIO112_MODE      GPIO_MODE_01
#define GPIO112_DIR       GPIO_DIR_IN
#define GPIO112_PULLEN    GPIO_PULL_DISABLE
#define GPIO112_PULL      GPIO_PULL_DOWN
#define GPIO112_DATAOUT   GPIO_OUT_ZERO
#define GPIO112_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 113
#define GPIO113_MODE      GPIO_MODE_01
#define GPIO113_DIR       GPIO_DIR_IN
#define GPIO113_PULLEN    GPIO_PULL_DISABLE
#define GPIO113_PULL      GPIO_PULL_DOWN
#define GPIO113_DATAOUT   GPIO_OUT_ZERO
#define GPIO113_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 114
#define GPIO114_MODE      GPIO_MODE_01
#define GPIO114_DIR       GPIO_DIR_IN
#define GPIO114_PULLEN    GPIO_PULL_DISABLE
#define GPIO114_PULL      GPIO_PULL_DOWN
#define GPIO114_DATAOUT   GPIO_OUT_ZERO
#define GPIO114_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 115
#define GPIO115_MODE      GPIO_MODE_DEFAULT
#define GPIO115_DIR       GPIO_DIR_IN
#define GPIO115_PULLEN    GPIO_PULL_ENABLE
#define GPIO115_PULL      GPIO_PULL_DOWN
#define GPIO115_DATAOUT   GPIO_OUT_ZERO
#define GPIO115_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 116
#define GPIO116_MODE      GPIO_MODE_01
#define GPIO116_DIR       GPIO_DIR_IN
#define GPIO116_PULLEN    GPIO_PULL_ENABLE
#define GPIO116_PULL      GPIO_PULL_DOWN
#define GPIO116_DATAOUT   GPIO_OUT_ZERO
#define GPIO116_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 117
#define GPIO117_MODE      GPIO_MODE_01
#define GPIO117_DIR       GPIO_DIR_IN
#define GPIO117_PULLEN    GPIO_PULL_ENABLE
#define GPIO117_PULL      GPIO_PULL_DOWN
#define GPIO117_DATAOUT   GPIO_OUT_ZERO
#define GPIO117_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 118
#define GPIO118_MODE      GPIO_MODE_01
#define GPIO118_DIR       GPIO_DIR_IN
#define GPIO118_PULLEN    GPIO_PULL_ENABLE
#define GPIO118_PULL      GPIO_PULL_DOWN
#define GPIO118_DATAOUT   GPIO_OUT_ZERO
#define GPIO118_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 119
#define GPIO119_MODE      GPIO_MODE_00
#define GPIO119_DIR       GPIO_DIR_OUT
#define GPIO119_PULLEN    GPIO_PULL_DISABLE
#define GPIO119_PULL      GPIO_PULL_DOWN
#define GPIO119_DATAOUT   GPIO_OUT_ZERO
#define GPIO119_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 120
#define GPIO120_MODE      GPIO_MODE_DEFAULT
#define GPIO120_DIR       GPIO_DIR_IN
#define GPIO120_PULLEN    GPIO_PULL_ENABLE
#define GPIO120_PULL      GPIO_PULL_DOWN
#define GPIO120_DATAOUT   GPIO_OUT_ZERO
#define GPIO120_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 121
#define GPIO121_MODE      GPIO_MODE_DEFAULT
#define GPIO121_DIR       GPIO_DIR_IN
#define GPIO121_PULLEN    GPIO_PULL_ENABLE
#define GPIO121_PULL      GPIO_PULL_DOWN
#define GPIO121_DATAOUT   GPIO_OUT_ZERO
#define GPIO121_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 122
#define GPIO122_MODE      GPIO_MODE_00
#define GPIO122_DIR       GPIO_DIR_IN
#define GPIO122_PULLEN    GPIO_PULL_ENABLE
#define GPIO122_PULL      GPIO_PULL_DOWN
#define GPIO122_DATAOUT   GPIO_OUT_ZERO
#define GPIO122_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 123
#define GPIO123_MODE      GPIO_MODE_00
#define GPIO123_DIR       GPIO_DIR_IN
#define GPIO123_PULLEN    GPIO_PULL_ENABLE
#define GPIO123_PULL      GPIO_PULL_DOWN
#define GPIO123_DATAOUT   GPIO_OUT_ZERO
#define GPIO123_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 124
#define GPIO124_MODE      GPIO_MODE_00
#define GPIO124_DIR       GPIO_DIR_OUT
#define GPIO124_PULLEN    GPIO_PULL_DISABLE
#define GPIO124_PULL      GPIO_PULL_DOWN
#define GPIO124_DATAOUT   GPIO_OUT_ZERO
#define GPIO124_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 125
#define GPIO125_MODE      GPIO_MODE_DEFAULT
#define GPIO125_DIR       GPIO_DIR_IN
#define GPIO125_PULLEN    GPIO_PULL_ENABLE
#define GPIO125_PULL      GPIO_PULL_DOWN
#define GPIO125_DATAOUT   GPIO_OUT_ZERO
#define GPIO125_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 126
#define GPIO126_MODE      GPIO_MODE_DEFAULT
#define GPIO126_DIR       GPIO_DIR_IN
#define GPIO126_PULLEN    GPIO_PULL_ENABLE
#define GPIO126_PULL      GPIO_PULL_DOWN
#define GPIO126_DATAOUT   GPIO_OUT_ZERO
#define GPIO126_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 127
#define GPIO127_MODE      GPIO_MODE_DEFAULT
#define GPIO127_DIR       GPIO_DIR_IN
#define GPIO127_PULLEN    GPIO_PULL_ENABLE
#define GPIO127_PULL      GPIO_PULL_DOWN
#define GPIO127_DATAOUT   GPIO_OUT_ZERO
#define GPIO127_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 128
#define GPIO128_MODE      GPIO_MODE_DEFAULT
#define GPIO128_DIR       GPIO_DIR_IN
#define GPIO128_PULLEN    GPIO_PULL_ENABLE
#define GPIO128_PULL      GPIO_PULL_DOWN
#define GPIO128_DATAOUT   GPIO_OUT_ZERO
#define GPIO128_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 129
#define GPIO129_MODE      GPIO_MODE_DEFAULT
#define GPIO129_DIR       GPIO_DIR_IN
#define GPIO129_PULLEN    GPIO_PULL_ENABLE
#define GPIO129_PULL      GPIO_PULL_DOWN
#define GPIO129_DATAOUT   GPIO_OUT_ZERO
#define GPIO129_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 130
#define GPIO130_MODE      GPIO_MODE_DEFAULT
#define GPIO130_DIR       GPIO_DIR_IN
#define GPIO130_PULLEN    GPIO_PULL_ENABLE
#define GPIO130_PULL      GPIO_PULL_DOWN
#define GPIO130_DATAOUT   GPIO_OUT_ZERO
#define GPIO130_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 131
#define GPIO131_MODE      GPIO_MODE_DEFAULT
#define GPIO131_DIR       GPIO_DIR_IN
#define GPIO131_PULLEN    GPIO_PULL_ENABLE
#define GPIO131_PULL      GPIO_PULL_DOWN
#define GPIO131_DATAOUT   GPIO_OUT_ZERO
#define GPIO131_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 132
#define GPIO132_MODE      GPIO_MODE_00
#define GPIO132_DIR       GPIO_DIR_IN
#define GPIO132_PULLEN    GPIO_PULL_ENABLE
#define GPIO132_PULL      GPIO_PULL_DOWN
#define GPIO132_DATAOUT   GPIO_OUT_ZERO
#define GPIO132_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 133
#define GPIO133_MODE      GPIO_MODE_00
#define GPIO133_DIR       GPIO_DIR_IN
#define GPIO133_PULLEN    GPIO_PULL_ENABLE
#define GPIO133_PULL      GPIO_PULL_DOWN
#define GPIO133_DATAOUT   GPIO_OUT_ZERO
#define GPIO133_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 134
#define GPIO134_MODE      GPIO_MODE_DEFAULT
#define GPIO134_DIR       GPIO_DIR_IN
#define GPIO134_PULLEN    GPIO_PULL_ENABLE
#define GPIO134_PULL      GPIO_PULL_DOWN
#define GPIO134_DATAOUT   GPIO_OUT_ZERO
#define GPIO134_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 135
#define GPIO135_MODE      GPIO_MODE_01
#define GPIO135_DIR       GPIO_DIR_IN
#define GPIO135_PULLEN    GPIO_PULL_ENABLE
#define GPIO135_PULL      GPIO_PULL_UP
#define GPIO135_DATAOUT   GPIO_OUT_ZERO
#define GPIO135_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 136
#define GPIO136_MODE      GPIO_MODE_01
#define GPIO136_DIR       GPIO_DIR_IN
#define GPIO136_PULLEN    GPIO_PULL_ENABLE
#define GPIO136_PULL      GPIO_PULL_UP
#define GPIO136_DATAOUT   GPIO_OUT_ZERO
#define GPIO136_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 137
#define GPIO137_MODE      GPIO_MODE_DEFAULT
#define GPIO137_DIR       GPIO_DIR_IN
#define GPIO137_PULLEN    GPIO_PULL_ENABLE
#define GPIO137_PULL      GPIO_PULL_DOWN
#define GPIO137_DATAOUT   GPIO_OUT_ZERO
#define GPIO137_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 138
#define GPIO138_MODE      GPIO_MODE_DEFAULT
#define GPIO138_DIR       GPIO_DIR_IN
#define GPIO138_PULLEN    GPIO_PULL_ENABLE
#define GPIO138_PULL      GPIO_PULL_DOWN
#define GPIO138_DATAOUT   GPIO_OUT_ZERO
#define GPIO138_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 139
#define GPIO139_MODE      GPIO_MODE_DEFAULT
#define GPIO139_DIR       GPIO_DIR_IN
#define GPIO139_PULLEN    GPIO_PULL_ENABLE
#define GPIO139_PULL      GPIO_PULL_DOWN
#define GPIO139_DATAOUT   GPIO_OUT_ZERO
#define GPIO139_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 140
#define GPIO140_MODE      GPIO_MODE_DEFAULT
#define GPIO140_DIR       GPIO_DIR_IN
#define GPIO140_PULLEN    GPIO_PULL_ENABLE
#define GPIO140_PULL      GPIO_PULL_DOWN
#define GPIO140_DATAOUT   GPIO_OUT_ZERO
#define GPIO140_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 141
#define GPIO141_MODE      GPIO_MODE_DEFAULT
#define GPIO141_DIR       GPIO_DIR_IN
#define GPIO141_PULLEN    GPIO_PULL_ENABLE
#define GPIO141_PULL      GPIO_PULL_DOWN
#define GPIO141_DATAOUT   GPIO_OUT_ZERO
#define GPIO141_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 142
#define GPIO142_MODE      GPIO_MODE_DEFAULT
#define GPIO142_DIR       GPIO_DIR_IN
#define GPIO142_PULLEN    GPIO_PULL_ENABLE
#define GPIO142_PULL      GPIO_PULL_DOWN
#define GPIO142_DATAOUT   GPIO_OUT_ZERO
#define GPIO142_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 143
#define GPIO143_MODE      GPIO_MODE_DEFAULT
#define GPIO143_DIR       GPIO_DIR_IN
#define GPIO143_PULLEN    GPIO_PULL_ENABLE
#define GPIO143_PULL      GPIO_PULL_DOWN
#define GPIO143_DATAOUT   GPIO_OUT_ZERO
#define GPIO143_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 144
#define GPIO144_MODE      GPIO_MODE_DEFAULT
#define GPIO144_DIR       GPIO_DIR_IN
#define GPIO144_PULLEN    GPIO_PULL_ENABLE
#define GPIO144_PULL      GPIO_PULL_DOWN
#define GPIO144_DATAOUT   GPIO_OUT_ZERO
#define GPIO144_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 145
#define GPIO145_MODE      GPIO_MODE_DEFAULT
#define GPIO145_DIR       GPIO_DIR_IN
#define GPIO145_PULLEN    GPIO_PULL_ENABLE
#define GPIO145_PULL      GPIO_PULL_DOWN
#define GPIO145_DATAOUT   GPIO_OUT_ZERO
#define GPIO145_DATAINV   GPIO_DATA_UNINV

//Configureation for Pin 146
#define GPIO146_MODE      GPIO_MODE_DEFAULT
#define GPIO146_DIR       GPIO_DIR_IN
#define GPIO146_PULLEN    GPIO_PULL_ENABLE
#define GPIO146_PULL      GPIO_PULL_DOWN
#define GPIO146_DATAOUT   GPIO_OUT_ZERO
#define GPIO146_DATAINV   GPIO_DATA_UNINV



#endif /* __CUST_GPIO_BOOT_H__ */


