

#ifndef _SLIC_BUILD_H_
#define _SLIC_BUILD_H_

#ifndef SLIC_PRODUCTION_BUILD
#define SLIC_PRODUCTION_BUILD			1
#endif
#ifndef SLIC_FAILURE_RESET
#define SLIC_FAILURE_RESET			1
#endif
#define DBG                         1
#ifndef SLIC_ASSERT_ENABLED
#define SLIC_ASSERT_ENABLED			1
#endif
#ifndef SLIC_MCAST_ENABLED
#define SLIC_MCAST_ENABLED			1
#endif
#ifndef SLIC_GET_STATS_ENABLED
#define SLIC_GET_STATS_ENABLED			1
#endif
#ifndef SLIC_GET_STATS_TIMER_ENABLED
#define SLIC_GET_STATS_TIMER_ENABLED		0
#endif
#ifndef SLIC_PING_TIMER_ENABLED
#define SLIC_PING_TIMER_ENABLED		1
#endif
#ifndef SLIC_IOCTL_SUPPORT_ENABLED
#define SLIC_IOCTL_SUPPORT_ENABLED		1
#endif
#ifndef ATK_DEBUG
#define ATK_DEBUG				1
#endif
#ifndef SLIC_POWER_MANAGEMENT_ENABLED
#define SLIC_POWER_MANAGEMENT_ENABLED		0
#endif
#ifndef SLIC_INTERRUPT_PROCESS_LIMIT
#define SLIC_INTERRUPT_PROCESS_LIMIT		1
#endif
#ifndef LINUX_FREES_ADAPTER_RESOURCES
#define LINUX_FREES_ADAPTER_RESOURCES		1
#endif
#ifndef SLIC_OFFLOAD_IP_CHECKSUM
#define SLIC_OFFLOAD_IP_CHECKSUM		1
#endif
#ifndef SLIC_POWER_MANAGEMENT_ENABLED
#define SLIC_POWER_MANAGEMENT_ENABLED		0
#endif
#ifndef STATS_TIMER_INTERVAL
#define STATS_TIMER_INTERVAL			2
#endif
#ifndef PING_TIMER_INTERVAL
#define PING_TIMER_INTERVAL			1
#endif

#endif   /* _SLIC_BUILD_H_  */
