


#ifndef __ASM_ARCH_MXC_BOARD_MX31LITE_H__
#define __ASM_ARCH_MXC_BOARD_MX31LITE_H__

#define MXC_MAX_EXP_IO_LINES	16



#define SDRAM_MEM_SIZE		SZ_128M
#define MXC_MBX_MEM_SIZE	SZ_16M
#define MEM_SIZE		(SDRAM_MEM_SIZE - MXC_MBX_MEM_SIZE)

#define MXC_LL_UART_PADDR	UART1_BASE_ADDR
#define MXC_LL_UART_VADDR	AIPS1_IO_ADDRESS(UART1_BASE_ADDR)

#endif /* __ASM_ARCH_MXC_BOARD_MX31ADS_H__ */

