
#ifndef __MT6516_MM_MEM_H__
#define __MT6516_MM_MEM_H__

#define INTERNAL_SRAM_DEVNAME "MT6516_Int_SRAM"

typedef enum 
{
    INTERNAL_SRAM_PNG_DECODER = 1,    
    INTERNAL_SRAM_JPEG_DECODER = 2,
    INTERNAL_SRAM_H264_DECODER_MC_LINE_BUF = 3,
    INTERNAL_SRAM_H264_DECODER_MC_MV_BUFFER = 4,
    INTERNAL_SRAM_H264_DECODER_DEC_DEB_BUF = 5,
    INTERNAL_SRAM_H264_DECODER_DEC_DEB_DAT_BUF0 = 6,
    INTERNAL_SRAM_H264_DECODER_DEC_DEB_DAT_BUF1 = 7,
    INTERNAL_SRAM_H264_DECODER_CALVC = 8,
    INTERNAL_SRAM_MPEG4_DECODER_DATA_STORE = 9,
    INTERNAL_SRAM_MPEG4_DECODER_DACP = 10,
    INTERNAL_SRAM_MPEG4_DECODER_MVP = 11,
    INTERNAL_SRAM_MPEG4_DECODER_QS = 12,
    INTERNAL_SRAM_MPEG4_ENCODER = 13,
    INTERNAL_SRAM_IDP_IRT0 = 14,
    INTERNAL_SRAM_IDP_IRT1 = 15,
    INTERNAL_SRAM_IDP_IRT3 = 16,
    INTERNAL_SRAM_IDP_VDO_ENC_WDMA = 17,
    INTERNAL_SRAM_IDP_JPEG_DMA = 18,
    INTERNAL_SRAM_IDP_PRZ = 19,
    INTERNAL_SRAM_IDP_MP4DEBLK = 20, 
    INTERNAL_SRAM_IDP_PRZ_MCU = 21,
    INTERNAL_SRAM_MAX_USING_INTERNAL_SRAM_DRIVER = 0xFFFFFFFF
} USING_INTERNAL_SRAM_DRIVER;

unsigned int alloc_internal_sram(USING_INTERNAL_SRAM_DRIVER driver_module, UINT32 size, UINT32 byte_alignment);
void free_internal_sram(USING_INTERNAL_SRAM_DRIVER driver_module, UINT32 phy_addr);

#endif //__MT6516_MM_MEM_H__
