obj-y := system.o core.o dma.o mt6516_devs.o mt6516_pll.o gpio.o mt6516_intr.o gpt.o mt6516_mm_mem.o MT6516_PM_api.o MT6516_PM_Log.o MT6516_sleep.o mt6516_slpctrl.o mt6516_ISP.o mt6516_IDP.o mt6516_timer.o mt6516_wdt.o mt6516_mm_queue.o mt6516_busmonitor.o mt6516_boot.o mtkpm.o gpio_init.o
         
#obj-m := ccci.o ccci_md.o ccci_tty.o ccci_fs.o ccci_pmic.o mt6516_sec.o
obj-n :=
obj-  :=

obj-$(CONFIG_AEE_FEATURE) += aed.o
obj-y += board.o mt_rfkill.o mt_bt.o
