obj-y := core.o mt3351_pmu.o mt3351_pll.o mt3351_pdn.o gpio.o dma.o gpt.o \
         mt3351_pwrkey.o mt3351_wdt.o mt3351_devs.o mt3351_sleep.o \
         mt3351_slpctrl.o mt3351_cp15.o system.o mt3351_dvfs.o \
         dvfs_switchCLK.o pwm.o
obj-m :=
obj-n :=
obj-  :=

obj-$(CONFIG_MT3351_EVB_BOARD) += board-evb.o
obj-$(CONFIG_MT3351_EVZ_BOARD) += board-evz.o
obj-$(CONFIG_MT3351_EVK_BOARD) += board-43evk.o
