obj-$(CONFIG_SOUND_MT6516) += yusu_fake_read.o yusu_android_sound.o yusu_asm.o yusu_ana.o

obj-$(CONFIG_MT6516_EVB_BOARD)    += headset/yusu_android_evb_headset.o
obj-$(CONFIG_MT6516_PHONE_BOARD)  += headset/yusu_android_gw616_headset.o
obj-$(CONFIG_MT6516_GEMINI_BOARD) += headset/yusu_android_gemini_headset.o
obj-$(CONFIG_MT6516_OPPO_BOARD)   += headset/yusu_android_oppo_headset.o
obj-$(CONFIG_MT6516_E1K_BOARD)   += headset/yusu_android_e1k_headset.o


#ats5500_ARM9.lib

# EOF
